# Generated by Django 3.2.9 on 2021-11-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snackapp', '0002_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='prodname',
        ),
    ]
