# Generated by Django 3.2.9 on 2021-11-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snackapp', '0004_auto_20211122_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
